core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.decorators import login_required


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('fitness.urls')),
]

fitness/models.py
from django.db import models
from django.utils import timezone
from dateutil.relativedelta import relativedelta

class Trainer(models.Model):
    full_name = models.CharField(max_length=100)
    registration_date = models.DateField(default=timezone.now)
    monthly_fee = models.IntegerField()
    student_fee = models.IntegerField()

    def __str__(self) -> str:
        return f"{self.full_name}"

class Tariffs(models.Model):
    PRICING_TYPE_CHOICES = [
        ('Daily', 'Daily'),
        ('Monthly', 'Monthly'),
    ]
    
    name = models.CharField(max_length=30, null=True)
    type = models.CharField(max_length=10, choices=PRICING_TYPE_CHOICES)
    month_duration = models.IntegerField(null=True, blank=True)
    price = models.IntegerField()

    def __str__(self) -> str:
        return f"{self.name}"

class Student(models.Model):
    full_name = models.CharField(max_length=100)
    registration_date = models.DateField(default=timezone.now)
    tariffs = models.ForeignKey(Tariffs, on_delete=models.CASCADE, null=True, blank=True)
    trainer = models.ForeignKey('Trainer', on_delete=models.CASCADE, null=True, blank=True)
    payment = models.IntegerField(default=0)
    end_date = models.DateField(null=True, blank=True)
    is_renewed = models.BooleanField(default=False)

    def calculate_payment(self):
        payment = 0.0  # Initially, the payment is reset

        if self.tariffs is not None:
            payment += self.tariffs.price  # Add the tariff price
            
            if self.tariffs.type == 'Monthly' and self.trainer:
                payment += self.trainer.student_fee * self.tariffs.month_duration
        
        # Update the payment in the `payment` variable
        self.payment = payment

    def calculate_end_date(self):
        # Calculation of end_date by adding months to month_duration on registration_date
        if self.tariffs and self.tariffs.type == 'Monthly':
            self.end_date = self.registration_date + relativedelta(months=self.tariffs.month_duration)

        if self.tariffs and self.tariffs.type == 'Daily':
            self.end_date = self.registration_date

    def save(self, *args, **kwargs):
        # Calculate the payment before saving
        self.calculate_payment()
        self.calculate_end_date()
        super().save(*args, **kwargs)

    def __str__(self) -> str:
        return f"{self.full_name}"

class Bar(models.Model):
    product_name = models.CharField(max_length=100)
    price = models.FloatField()
    stock_number = models.IntegerField()
    date = models.DateField(default=timezone.now)

    def __str__(self) -> str:
        return f"{self.product_name}"
    
class BarSold(models.Model):
    product_name = models.ForeignKey(Bar, on_delete=models.CASCADE, null=True, blank=True)
    date = models.DateField(default=timezone.now)
    price = models.FloatField()
    count = models.IntegerField()

    def __str__(self) -> str:
        return f"{self.product_name}"

templates/student/add_student.html
{% include "index.html" %}

{% block content %}
<style>
    form {
        max-width: 400px;
        margin: 0 auto;
        padding: 20px;
        background: #f9f9f9;
        border-radius: 8px;
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
    }

    input[type="text"],
    input[type="email"],
    input[type="date"],
    select {
        width: 100%;
        padding: 10px;
        margin: 5px 0;
        border: 1px solid #ccc;
        border-radius: 5px;
        box-sizing: border-box;
    }

    button[type="submit"] {
        background-color: #4CAF50;
        color: white;
        padding: 12px 20px;
        margin: 8px 0;
        border: none;
        border-radius: 4px;
        cursor: pointer;
        width: 100%;
    }

    button[type="submit"]:hover {
        background-color: #45a049;
    }
</style>

{% if messages %}
<div class="alert alert-success" role="alert">
    {% for message in messages %}
    {{ message }}
    {% endfor %}
</div>
{% endif %}

<br>
<form method="post">
    <h2>Add Member</h2>
    {% csrf_token %}
    <div class="form-group">
        <label for="id_full_name">Full Name:</label>
        {{ form.full_name }}
    </div>
    <div class="form-group">
        <label for="id_monthly_fee">Tariff:</label>
        {{ form.tariffs }}
    </div>
    <div class="form-group">
        <label for="id_student_fee">Trainer:</label>
        {{ form.trainer }}
    </div>
    <div class="form-group">
        <label for="id_registration_date">Registration Date:</label>
        {{ form.registration_date }}
    </div>
    <button type="submit">Add</button>
</form>

<br><br>
{% endblock content %}

templates/student/daily_student_list.html
{% include "index.html" %}

{% block content %}

<div class="container mt-5">
    <h2 class="text-center">Due Date Members</h2>
    <h4 class="text-center">
        ({{ today }}) 
    </h4>
    <br>
    <!-- <form method="GET" class="mb-3">
        <div class="form-inline mb-4">
            <input type="text" name="q" class="form-control mr-sm-2" placeholder="Axtarış adını daxil edin">
            <button class="btn btn-outline-primary my-2 my-sm-0" type="submit">Axtar</button>
            &nbsp;
            <a href="{% url 'daily_student_list' %}"><button class="btn btn-outline-primary my-2 my-sm-0" type="submit">Sıfırla</button>
            </a>
        </div>
    </form> -->
    <table class="table text-center">
        <thead>
            <tr>
                <th scope="col">№</th>
                <th scope="col">Full Name</th>
                <th scope="col">Registration Date</th>
                <th scope="col">End Date</th>
                <th scope="col">Months</th>
                <th scope="col">Trainer</th>
                <th scope="col">Payment</th>
            </tr>
        </thead>
        <tbody>
            {% for student in students %}
            <tr>
                <td>{{ forloop.counter }}</td>
                <td>{{ student.full_name }}</td>
                <td>{{ student.registration_date|date:"d/m/Y" }}</td>
                <td>{{ student.end_date|date:"d/m/Y" }}</td>
                <td>{{ student.tariffs }}</td>
                <td>{{ student.trainer|default:"---" }}</td>
                <td>${{ student.payment }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

<br>
<br>
{% endblock content %}

templates/student/student_list.html
{% include "index.html" %}

{% block content %}
<style>
    .end-date-today {
        color: red;
        font-weight: bold;
    }

    .end-date-past {
        color: grey;
    }

    .renewed {
        color: grey;
    }

    .table th, .table td {
        vertical-align: middle;
    }

    .modal-header, .modal-footer {
        background-color: #f8f9fa;
    }

    .modal-title {
        font-weight: bold;
    }

    .modal-body ul {
        list-style-type: none;
        padding: 0;
    }

    .modal-body li {
        margin-bottom: 10px;
    }

    /* Custom class for lighter table header */
    .thead-light-custom {
        background-color: #e9ecef; /* Light grey background */
        color: #212529; /* Dark text color for contrast */
    }
</style>

<div class="container mt-5">
    <h2 class="mb-4">Member List</h2>
    <div class="row">
        <div class="col-md-8">
            <form method="GET" class="mb-3">
                <div class="form-inline mb-4">
                    <input type="text" name="q" class="form-control mr-sm-2" style="width: 300px;" placeholder="Enter a search name">
                    <button class="btn btn-outline-primary my-2 my-sm-0" type="submit">Search</button>
                    &nbsp;
                    <a href="{% url 'student_list' %}">
                        <button class="btn btn-outline-secondary my-2 my-sm-0" type="button">Reset</button>
                    </a>
                </div>
            </form>
        </div>
        <div class="col-md-4 text-right">
            <button class="btn btn-danger my-2 my-sm-0" data-toggle="modal" data-target="#warningModal">
                Upcoming End Dates
            </button>
        </div>
    </div>
    {% if grouped_students.items %}
    {% for month, data in grouped_students.items %}
    <div class="row mb-2">
        <div class="col-md-6 text-left">
            <h4>{{ month }}</h4>
        </div>
        <div class="col-md-6 text-right">
            <h4>Total Payment: ${{ data.total_payment }}</h4>
        </div>
    </div>
    <div class="table-responsive">
        <table class="table table-striped table-hover text-center mb-5">
            <thead class="thead-light-custom">
                <tr>
                    <th scope="col">№</th>
                    <th scope="col">Full Name</th>
                    <th scope="col">Registration Date</th>
                    <th scope="col">End Date</th>
                    <th scope="col">Months</th>
                    <th scope="col">Trainer</th>
                    <th scope="col">Payment</th>
                </tr>
            </thead>
            <tbody>
                {% for student in data.students %}
                <tr class="{% if student.is_renewed %}
                        renewed
                    {% elif student.end_date == today and student.tariffs.type != 'Daily' %}
                        end-date-today
                    {% elif student.end_date < today %}
                        end-date-past
                    {% elif student.tariffs.type == 'Daily' and student.end_date != today %}
                        end-date-past
                    {% endif %}">
                    <td>{{ forloop.counter }}</td>
                    <td>{{ student.full_name }}</td>
                    <td>{{ student.registration_date|date:"d/m/Y" }}</td>
                    <td>{{ student.end_date|date:"d/m/Y" }}</td>
                    <td>{{ student.tariffs }}</td>
                    <td>{{ student.trainer|default:"---" }}</td>
                    <td>${{ student.payment }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    {% endfor %}
    {% else %}
        <p class="text-center">No members were found matching your search.</p>
    {% endif %}

    <!-- Modal -->
    <div class="modal fade" id="warningModal" tabindex="-1" role="dialog" aria-labelledby="warningModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="warningModalLabel">Upcoming End Dates</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <ul>
                        {% for student in students_near_end_date %}
                        {% if student.tariffs.type != 'Daily' and not student.is_renewed %}
                        <li>{{ student.full_name }} - Payment Date: {{ student.end_date|date:"d/m/Y" }}</li>
                        {% endif %}
                        {% endfor %}
                    </ul>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

templates/student/student_panel.html
{% include "index.html" %}

{% block content %}

<style>
    .end-date-today {
        color: red;
        font-weight: bold;
    }

    .end-date-past {
        color: grey;
    }

    .renewed {
        color: grey;
    }

    .table th, .table td {
        vertical-align: middle;
    }

    /* Custom class for lighter table header */
    .thead-light-custom {
        background-color: #e9ecef; /* Light grey background */
        color: #212529; /* Dark text color for contrast */
    }
</style>

<div class="container mt-5">
    <h2 class="mb-4">Member Panel</h2>
    <form method="GET" class="mb-3">
        <div class="form-inline mb-4">
            <input type="text" name="q" class="form-control mr-sm-2" style="width: 300px;" placeholder="Enter a search name">
            <button class="btn btn-outline-primary my-2 my-sm-0" type="submit">Search</button>
            &nbsp;
            <a href="{% url 'student_panel' %}">
                <button class="btn btn-outline-secondary my-2 my-sm-0" type="button">Reset</button>
            </a>
        </div>
    </form>
    {% if grouped_students.items %}
    {% for month, data in grouped_students.items %}
    <div class="row mb-2">
        <div class="col-md-6 text-left">
            <h4>{{ month }}</h4>
        </div>
        <div class="col-md-6 text-right">
            <h4>Total Payment: ${{ data.total_payment }}</h4>
        </div>
    </div>
    <div class="table-responsive">
        <table class="table table-striped table-hover text-center mb-5">
            <thead class="thead-light-custom">
                <tr>
                    <th scope="col">№</th>
                    <th scope="col">Full Name</th>
                    <th scope="col">Registration Date</th>
                    <th scope="col">End Date</th>
                    <th scope="col">Months</th>
                    <th scope="col">Trainer</th>
                    <th scope="col">Payment</th>
                    <th scope="col">Operations</th>
                </tr>
            </thead>
            <tbody>
                {% for student in data.students %}
                <tr class="{% if student.is_renewed %}
                        renewed
                    {% elif student.end_date == today and student.tariffs.type != 'Daily' %}
                    end-date-today
                {% elif student.end_date < today %}
                    end-date-past
                {% elif student.tariffs.type == 'Daily' and student.end_date != today %}
                        end-date-past
                    {% endif %}">
                    <td>{{ forloop.counter }}</td>
                    <td>{{ student.full_name }}</td>
                    <td>{{ student.registration_date|date:"d/m/Y" }}</td>
                    <td>{{ student.end_date|date:"d/m/Y" }}</td>
                    <td>{{ student.tariffs }}</td>
                    <td>{{ student.trainer|default:"---" }}</td>
                    <td>${{ student.payment }}</td>
                    <td>
                        <a href="{% url 'renew_student' student.pk %}" class="btn btn-sm btn-success" onclick="return confirm('Are you sure you want to renew this student?')">Renew</a>
                        <a href="{% url 'update_student' student.pk %}" class="btn btn-sm btn-info">Edit</a>
                        <a href="{% url 'delete_student' student.pk %}" class="btn btn-sm btn-danger" onclick="return confirm('Are you sure you want to delete this student?')">Delete</a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    {% endfor %}
    {% else %}
        <p class="text-center">No members were found matching your search.</p>
    {% endif %}
</div>

<br>
<br>
{% endblock content %}

templates/student/update_student.html
{% extends 'index.html' %}

{% block content %}
<style>
    form {
        max-width: 400px;
        margin: 0 auto;
        padding: 20px;
        background: #f9f9f9;
        border-radius: 8px;
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
    }

    input[type="text"],
    input[type="date"],
    input[type="number"],
    select {
        width: 100%;
        padding: 10px;
        margin: 5px 0;
        border: 1px solid #ccc;
        border-radius: 5px;
        box-sizing: border-box;
        outline: none;
        transition: border-color 0.3s ease;
    }

    input[type="checkbox"] {
        width: 1em;
        height: 1rem;
        accent-color: green;
        }

    input[type="text"]:focus,
    input[type="date"]:focus,
    input[type="number"]:focus,
    select:focus {
        border-color: #4CAF50;
    }

    button[type="submit"] {
        background-color: #4CAF50;
        color: white;
        padding: 12px 20px;
        margin: 8px 0;
        border: none;
        border-radius: 4px;
        cursor: pointer;
        width: 100%;
    }

    button[type="submit"]:hover {
        background-color: #45a049;
    }

    label {
        font-weight: bold;
        margin-bottom: 5px;
    }
</style>

<div class="container mt-4">
    <form method="post">
        <h2 class="mb-4" style="color: rgb(82, 124, 222);">Edit Member</h2>
        {% csrf_token %}
        <div class="form-group">
            <label for="id_full_name">Full Name:</label>
            {{ form.full_name }}
        </div>
        <div class="form-group">
            <label for="id_monthly_fee">Tariff:</label>
            {{ form.tariffs }}
        </div>
        <div class="form-group">
            <label for="id_student_fee">Trainer:</label>
            {{ form.trainer }}
        </div>
        <div class="form-group">
            <label for="id_registration_date">Registration Date:</label>
            {{ form.registration_date }}
        </div>
        <div class="form-group">
            <label for="id_is_renewed">ReNew:</label>
            {{ form.is_renewed }}
        </div>
        <button type="submit" class="btn btn-primary">Edit</button>
    </form>
</div>

<br><br>
{% endblock %}