core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.decorators import login_required


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('fitness.urls')),
]

fitness/models.py
from django.db import models
from django.utils import timezone
from dateutil.relativedelta import relativedelta

class Trainer(models.Model):
    full_name = models.CharField(max_length=100)
    registration_date = models.DateField(default=timezone.now)
    monthly_fee = models.IntegerField()
    student_fee = models.IntegerField()

    def __str__(self) -> str:
        return f"{self.full_name}"

class Tariffs(models.Model):
    PRICING_TYPE_CHOICES = [
        ('Daily', 'Daily'),
        ('Monthly', 'Monthly'),
    ]
    
    name = models.CharField(max_length=30, null=True)
    type = models.CharField(max_length=10, choices=PRICING_TYPE_CHOICES)
    month_duration = models.IntegerField(null=True, blank=True)
    price = models.IntegerField()

    def __str__(self) -> str:
        return f"{self.name}"

class Student(models.Model):
    full_name = models.CharField(max_length=100)
    registration_date = models.DateField(default=timezone.now)
    tariffs = models.ForeignKey(Tariffs, on_delete=models.CASCADE, null=True, blank=True)
    trainer = models.ForeignKey('Trainer', on_delete=models.CASCADE, null=True, blank=True)
    payment = models.IntegerField(default=0)
    end_date = models.DateField(null=True, blank=True)
    is_renewed = models.BooleanField(default=False)

    def calculate_payment(self):
        payment = 0.0  # Initially, the payment is reset

        if self.tariffs is not None:
            payment += self.tariffs.price  # Add the tariff price
            
            if self.tariffs.type == 'Monthly' and self.trainer:
                payment += self.trainer.student_fee * self.tariffs.month_duration
        
        # Update the payment in the `payment` variable
        self.payment = payment

    def calculate_end_date(self):
        # Calculation of end_date by adding months to month_duration on registration_date
        if self.tariffs and self.tariffs.type == 'Monthly':
            self.end_date = self.registration_date + relativedelta(months=self.tariffs.month_duration)

        if self.tariffs and self.tariffs.type == 'Daily':
            self.end_date = self.registration_date

    def save(self, *args, **kwargs):
        # Calculate the payment before saving
        self.calculate_payment()
        self.calculate_end_date()
        super().save(*args, **kwargs)

    def __str__(self) -> str:
        return f"{self.full_name}"

class Bar(models.Model):
    product_name = models.CharField(max_length=100)
    price = models.FloatField()
    stock_number = models.IntegerField()
    date = models.DateField(default=timezone.now)

    def __str__(self) -> str:
        return f"{self.product_name}"
    
class BarSold(models.Model):
    product_name = models.ForeignKey(Bar, on_delete=models.CASCADE, null=True, blank=True)
    date = models.DateField(default=timezone.now)
    price = models.FloatField()
    count = models.IntegerField()

    def __str__(self) -> str:
        return f"{self.product_name}"

templates/tariffs/add_tariffs.html
{% include "index.html" %}

{% block content %}
<style>
    form {
        max-width: 400px;
        margin: 0 auto;
        padding: 20px;
        background: #f9f9f9;
        border-radius: 8px;
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
    }

    input[type="text"],
    input[type="number"],
    select {
        width: 100%;
        padding: 10px;
        margin: 5px 0;
        border: 1px solid #ccc;
        border-radius: 5px;
        box-sizing: border-box;
    }

    button[type="submit"] {
        background-color: #4CAF50;
        color: white;
        padding: 12px 20px;
        margin: 8px 0;
        border: none;
        border-radius: 4px;
        cursor: pointer;
        width: 100%;
    }

    button[type="submit"]:hover {
        background-color: #45a049;
    }
</style>

{% if messages %}
<div class="alert alert-success" role="alert">
    {% for message in messages %}
    {{ message }}
    {% endfor %}
</div>
{% endif %}

<br>
<form method="post" action="{% url 'add_tariffs' %}">
    <h2>Add Tariff</h2>
    {% csrf_token %}
    <div class="form-group">
        <label for="id_name">Name:</label>
        {{ form.name }}
    </div>
    <div class="form-group">
        <label for="id_type">Type:</label>
        {{ form.type }}
    </div>
    <div class="form-group">
        <label for="id_month_duration">Month Duration:</label>
        {{ form.month_duration }}
    </div>
    <div class="form-group">
        <label for="id_price">Price:</label>
        {{ form.price }}
    </div>
    <button type="submit">Add</button>
</form>

<br><br>
{% endblock content %}

templates/tariffs/tariffs_panel.html
{% include "index.html" %}

{% block content %}

<div class="container mt-5">
    <h2 class="mb-4">Tarif Panel</h2>
    <table class="table text-center">
        <thead>
            <tr>
                <th scope="col">№</th>
                <th scope="col">Name</th>
                <th scope="col">Type</th>
                <th scope="col">Month</th>
                <th scope="col">Price</th>
                <th scope="col">Operations</th>
            </tr>
        </thead>
        <tbody>
            {% for tariff in tariffs %}
            <tr>
                <td>{{ forloop.counter }}</td>
                <td>{{ tariff.name }}</td>
                <td>{{ tariff.type }}</td>
                <td>{{ tariff.month_duration }}</td>
                <td>${{ tariff.price }}</td>
                <td>
                    <a href="{% url 'update_tariffs' tariff.pk %}" class="btn btn-sm btn-info">Edit</a>
                    <a href="{% url 'delete_tariffs' tariff.pk %}" class="btn btn-sm btn-danger" onclick="return confirm('Are you sure you want to delete this tariff?')">Delete</a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

<br>
<br>

{% endblock content %}

templates/tariffs/update_tariffs.html
{% extends 'index.html' %}

{% block content %}
<style>
    form {
        max-width: 400px;
        margin: 0 auto;
        padding: 20px;
        background: #f9f9f9;
        border-radius: 8px;
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
    }

    input[type="text"],
    input[type="date"],
    input[type="number"] {
        width: 100%;
        padding: 10px;
        margin: 5px 0;
        border: 1px solid #ccc;
        border-radius: 5px;
        box-sizing: border-box;
    }

    button[type="submit"] {
        background-color: #4CAF50;
        color: white;
        padding: 12px 20px;
        margin: 8px 0;
        border: none;
        border-radius: 4px;
        cursor: pointer;
        width: 100%;
    }

    button[type="submit"]:hover {
        background-color: #45a049;
    }

    label {
        font-weight: bold;
        margin-bottom: 5px;
    }
</style>

<div class="container mt-4">
<form method="post">
    <h2 class="mb-4" style="color: rgb(82, 124, 222);">Edit Tariff</h2>
    {% csrf_token %}
    <div class="form-group">
        <label for="id_name">Name:</label>
        {{ form.name }}
    </div>
    <div class="form-group">
        <label for="id_type">Type:</label>
        {{ form.type }}
    </div>
    <div class="form-group">
        <label for="id_month_duration">Month Duration:</label>
        {{ form.month_duration }}
    </div>
    <div class="form-group">
        <label for="id_price">Price:</label>
        {{ form.price }}
    </div>
    <button type="submit" class="btn btn-primary">Edit</button>
</form>
</div>
{% endblock %}